### ISSUE TITLE
Remove [Required] from ComposeFileYaml to enable use of default compose file and overrides

### ISSUE THREAD

**Issue by rhessinger** [Inedo/inedox-docker#14]

**Comment by rhessinger** [comment]
@SilverXXX This is what will track your change.

**Comment by SilverXXX** [comment]
I tried it and it seems buildmaster is not loading it, maybe due to  "_inedoSdkVersion": "1.10.0" in upack.json?

**Comment by rhessinger** [comment]
@SilverXXX Sorry about that.  The branch this is committed to is `1.7`.  Looks like I forgot to update the branch when I kicked off the build.  Here is a link to the proper extensions build [1.7.3-CI.12](https://proget.inedo.com/feeds/PrereleaseExtensions/inedox/Docker/1.7.3-CI.12).  Can you please give this a try?

**Comment by SilverXXX** [comment]
Everything seems fine now
